version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '00000000'
    networks:
      - pethub
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  pethub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pethub
    networks:
      - pethub
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pethub?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: '00000000'

networks:
  pethub:

volumes:
  mysql_data:
